# The URL the site will be built for
base_url = "https://h0ffmann.at"
title = "sebastian-hoffmann"
theme = "after-dark"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true


# Put all your custom variables here
taxonomies = [
  {name = "tags", feed = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
[extra]

after_dark_menu = [
  {url = "$BASE_URL", name = "home"},
  {url = "$BASE_URL/about", name = "about me"},
  {url = "$BASE_URL/tags", name = "tags"},
]

after_dark_title = "sebastian's space"
